apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# commonAnnotations:
#   argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: sandbox
    patch: |-
      - op: replace
        path: /metadata/annotations/openshift.io~1description
        value: "8Knot Dev Deployment"
      - op: replace
        path: /metadata/annotations/openshift.io~1display-name
        value: "Development 8Knot"
      - op: replace
        path: /metadata/name
        value: "dev-sandiego-explorer-osci-io"
  - target:
      kind: Ingress
      name: eightknot-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.eightknot.osci.io
  - target:
      kind: Route
      name: eightknot-app
    patch: |-
      - op: replace
        path: /spec/host
        value: dev.eightknot.osci.io
