---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: check-byte-order-marker
      - id: check-case-conflict
      # - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

#  # Enable this to enforce docstring styling
#  - repo: https://github.com/pycqa/pydocstyle.git
#    rev: 6.1.1
#    hooks:
#      - id: pydocstyle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.902
#    hooks:
#      - id: mypy
#        exclude: '^(docs|tasks|tests)|setup|job_manager\.py'
#        args: [--ignore-missing-imports]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ['--line-length=120']

#  # Enable this for more robust style checking
#  - repo: https://github.com/pycqa/flake8
#    rev: '5.0.4'  # pick a git hash / tag to point to
#    hooks:
#    -   id: flake8
#        additional_dependencies: ['pep8-naming']
#        # Ignore all format-related checks as Black takes care of those.
#        args: ['--ignore',
#               'E2,W5',
#               '--select',
#               'E,W,F,N',
#               '--max-line-length=120']
