FROM registry.access.redhat.com/ubi9/python-39

WORKDIR /8knot

# install required packages
COPY ./requirements.txt /8knot/
RUN pip3 install --no-cache-dir -r requirements.txt

# copy the contents of current file into the
# working directory.
COPY ./ /8knot/

# run worker
CMD ["celery", "-A", "app:celery_app", "flower"]
