FROM registry.access.redhat.com/ubi9/python-39

EXPOSE 8050

WORKDIR /8knot

COPY ./requirements.txt /8knot/
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./ /8knot/

# Description of how to choose the number of workers and threads.
# common wisdom is (2*CPU)+1 workers:
# https://medium.com/building-the-system/gunicorn-3-means-of-concurrency-efbb547674b7
CMD [ "gunicorn", "--bind", ":8050", "app:server", "--workers", "4", "--threads", "2" ]
