FROM registry.access.redhat.com/ubi9/python-39

EXPOSE 8050

RUN pip --no-cache-dir install pipenv

WORKDIR /8knot

COPY ./requirements.txt /8knot/
RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./ /8knot/

# run worker
CMD ["celery", "-A", "app:celery_app", "worker", "--loglevel=WARNING"]
