---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"postgresql:13-el8","namespace":"openshift"},"fieldPath":"spec.template.spec.containers[?(@.name==\"postgresql\")].image","pause":"true"}]
  name: eightknot-postgres-cache
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: eightknot-postgres-cache
  template:
    metadata:
      labels:
        name: eightknot-postgres-cache
    spec:
      containers:
        # TODO: decide to use openshift postgres image
        # image: quay.io/enterprisedb/postgresql:13
        - image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:13-el8
          name: postgresql
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-cache-data
          envFrom:
            - secretRef:
                name: eightknot-postgres
      restartpolicy: always
      resources:
        limits:
          memory: 4Gi
        requests:
          memory: 128Mi
      volumes:
        - name: empty
          emptyDir: {}
        - name: postgres-cache-data
          persistentVolumeClaim:
            claimName: eightknot-postgres-cache-data
---
apiVersion: v1
kind: Service
metadata:
  # TODO: define best default for openshift and docker compose
  name: postgres-cache
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: eightknot-postgres-cache
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eightknot-postgres-cache-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  volumeMode: Filesystem
