apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    app.kubernetes.io/part-of: eightknot-app
  name: eightknot-redis
stringData:
  REDIS_PASSWORD: secretpassword
  # kludge - rename to REDIS_HOST, REDIS_PORT
  REDIS_SERVICE_HOST: eightknot-redis
