apiVersion: v1
kind: Secret
metadata:
  name: augur-config
  labels:
    app.kubernetes.io/part-of: eightknot-app
type: Opaque
stringData:
  AUGUR_DATABASE: astros
  AUGUR_HOST: chaoss.tv
  AUGUR_PASSWORD: '!xpk98T6?bK'
  AUGUR_PORT: '5432'
  AUGUR_SCHEMA: augur_data
  AUGUR_USERNAME: eightknot
  AUGUR_LOGIN_ENABLED: true
  OAUTH_CLIENT_NAME: augur
  OAUTH_AUTHORIZE_URL: 'https://eightknot.chaoss.tv/user/authorize'
  OAUTH_TOKEN_URL: 'https://eightknot.chaoss.tv/api/unstable/user/session/generate'
  OAUTH_REDIRECT_URL: 'https://dev.eightknot.osci.io/authorize'
  # fix: invalid env var
  # 8KNOT_DEBUG: 'True'
